[versions]
scala-version = "3.2.1"
scalatest-version = "3.2.15"
# insert the versions of the dependencies here...

[libraries]
scala = { module = "org.scala-lang:scala3-library_3", version.ref = "scala-version" }
scalatest = { module = "org.scalatest:scalatest_3", version.ref = "scalatest-version" }
# insert the dependencies here...

[bundles]
# insert groups of dependencies here...

[plugins]
# insert references to plugin here...